modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
[[mods]]
modId="snowed_over"
version="1.19-1.0.0"
displayName="Snowed Over"
logoFile="snowed_over.png"
credits="Orcinus"
authors="Ninni"
description='''
A *cool* mod that plans to add small features to the snowy biomes
'''
[[dependencies.snowed_over]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.snowed_over]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
